apiVersion: apps/v1
kind: Deployment
metadata:
  name: trdl-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trdl-sinch
  template:
    metadata:
      labels:
        app: trdl-sinch
    spec:
      nodeSelector:
        failure-domain.beta.kubernetes.io/region: us-east-1
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: failure-domain.beta.kubernetes.io/zone
                operator: In
                values:
                - us-east-1a
                - us-east-1b
                - us-east-1c
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: trdl-sinch
