apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: trdl-synch-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: my-webapp.example.com
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: my-webapp-service
                port:
                  number: 80