apiVersion: v1
kind: Service
metadata:
  name: {{ include "trdl-synch.fullname" . }}
  labels:
    app: {{ include "trdl-synch.name" . }}
spec:
  selector:
    app: {{ include "trdl-synch.name" . }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer